version: 0.2

phases:
  
  install:
    runtime-versions:
      java: latest
  
  pre-build:
    commands:
      - rm -rf target
  
  build:
    commands:
       - mvn compile
       - mvn test surefirefire-report:report
  
  post-build:
    commands:
        - mvn package
  
reports:
    files:
      - 'target/surefire-report/*'

artifacts:
    files: 
      - 'target/*.jar'
    discard-paths: yes