version: 0.2

phases:
  install:
    runtime-versions:
      java: latest
  
  pre_build:
    commands:
      - rm -rf target
  
  build:
    commands:
       - mvn compile
       - mvn test surefire-report:report
  
  post_build:
    commands:
        - mvn package
  
reports:
  reportJUNIT:
    files:
      - "**/*"
    base-directory: 'target/surefire-reports'
    discard-paths: no
artifacts:
    files: 
      - "*.jar"
    base-directory: 'target'
    discard-paths: yes
