version: '3'
services:
  maven:
    build: .
    volumes:
      - '.:/jmapp'
    ports:
      - '6060:8080'
  gradle:
    build: ./GradleDocker/
    volumes:
      - '.:/jmapp'
    ports:
      - '4040:8080'
  
